apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ftest-0807 
  janus-idp.io/tekton: ftest-0807
  backstage.io/kubernetes-id: ftest-0807
  backstage.io/kubernetes-namespace: rhdh 
  app.kubernetes.io/part-of: ftest-0807
resources: 
- application-dev.yaml