apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ftest-0807
  janus-idp.io/tekton: ftest-0807
  backstage.io/kubernetes-id: ftest-0807
  backstage.io/kubernetes-namespace: rhdh 
  app.kubernetes.io/part-of: ftest-0807
resources: 
- initialize-namespace.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml